In [6]:
# Vectores, matrices, norma y producto escalar

import numpy as np 

# Vector 
v = np.array([2, 3])

# Escalado
v_scaled = 5 * v

print("Vector original: ", v)
print("Vector escalado: ", v_scaled)

# Matriz
M = np.array([[1, 2], [3, 4]])

# Multiplicacion matriz-vector
result = M @ v
print("Matriz:\n", M)
print("Resultado M * v:", result)

# Norma
norm_v = np.linalg.norm(v)
print("Norma del vector:", norm_v)

# Producto punto
dot = np.dot(v, v_scaled)
print("Producto punto v . v_scaled:", dot)

Vector original:  [2 3]
Vector escalado:  [10 15]
Matriz:
 [[1 2]
 [3 4]]
Resultado M * v: [ 8 18]
Norma del vector: 3.605551275463989
Producto punto v . v_scaled: 65


In [8]:
# Suma y resta de vectores y matrices

a = np.array([1, 2])
b = np.array([3, 4])

print("Suma: ", a + b)
print("Resta: ", a - b)

M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

print("Suma matrices:\n", M1 + M2)

Suma:  [4 6]
Resta:  [-2 -2]
Suma matrices:
 [[ 6  8]
 [10 12]]


In [9]:
# Transpuesta de una matriz

M = np.array([[1, 2], [3, 4]])
print("Matriz transpuesta:\n", M.T)

Matriz transpuesta:
 [[1 3]
 [2 4]]


In [12]:
# Producto matriz-matriz, determinante, inversa de una matriz
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Producto A*B:\n", A @ B)

det_A = np.linalg.det(A)
print("Determinante de A:", det_A)

A_inv = np.linalg.inv(A)
print("Inversa de A:\n", A_inv)

Producto A*B:
 [[19 22]
 [43 50]]
Determinante de A: -2.0000000000000004
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
